### PR TITLE
Add Fastlane Files for F-Droid Inclusion

### PR DESCRIPTION
**Pull request by ZachMyers3**
Hello!

I saw [this issue](https://github.com/izderadicka/audioserve-android/issues/9) which lead me to [this issue on F-Droid's repo](https://gitlab.com/fdroid/rfp/-/issues/1408) on the status of including this.

I've added the needed files for them to automatically pull the information in the MR. I've also bumped a version and added a changelog for this version bump as well as an example.

I also saw [this GitHub action](https://github.com/ashutoshgngwr/validate-fastlane-supply-metadata) to validate this information, but hesitated to add to your repo, as I see you're using TravisCI.

Let me know if you have any input, thanks!

### CODE REVIEW

**Comment by izderadicka** [comment]
Do we need to increase version number, as code is not changing?

Github action would be nice,  I need to move out of TravisCI  due to their change in policy for open source projects.

Thanks for PR.

**Comment by ZachMyers3** [comment]
Good point, I've pulled it back accordingly. 

Maybe a migration to Github Actions would be a separate issue then, so I'll hold of on doing that.

**Comment by izderadicka** [comment]
Thanks a lot, I merged changes.
Also opening Issue for CI migration to GH Actions.

**Comment by ZachMyers3** [comment]
Thanks!

You can probably close #20 also, as we were both accomplishing the same things.

**Pull request merged**
